In [40]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.model_selection import train_test_split , GridSearchCV 
from sklearn.preprocessing import StandardScaler 
from sklearn.metrics import accuracy_score ,classification_report , confusion_matrix 
import xgboost as xgb
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error, r2_score



In [42]:
df = pd.read_csv("/home/teddy/Music/Java/dataset1/house_price_regression_dataset.csv")

In [43]:
df

Square_Footage  Num_Bedrooms  Num_Bathrooms  Year_Built  Lot_Size  \
0              1360             2              1        1981  0.599637   
1              4272             3              3        2016  4.753014   
2              3592             1              2        2016  3.634823   
3               966             1              2        1977  2.730667   
4              4926             2              1        1993  4.699073   
..              ...           ...            ...         ...       ...   
995            3261             4              1        1978  2.165110   
996            3179             1              2        1999  2.977123   
997            2606             4              2        1962  4.055067   
998            4723             5              2        1950  1.930921   
999            3268             4              2        1983  3.108790   

     Garage_Size  Neighborhood_Quality   House_Price  
0              0                     5  2.623829e+05  
1              1                     6  9.852609e+05  
2              0                     9  7.779774e+05  
3              1                     8  2.296989e+05  
4              0                     8  1.041741e+06  
..           ...                   ...           ...  
995            2                    10  7.014940e+05  
996            1                    10  6.837232e+05  
997            0                     2  5.720240e+05  
998            0                     7  9.648653e+05  
999            2                     2  7.425993e+05  

[1000 rows x 8 columns]

In [44]:
df.head()

Square_Footage  Num_Bedrooms  Num_Bathrooms  Year_Built  Lot_Size  \
0            1360             2              1        1981  0.599637   
1            4272             3              3        2016  4.753014   
2            3592             1              2        2016  3.634823   
3             966             1              2        1977  2.730667   
4            4926             2              1        1993  4.699073   

   Garage_Size  Neighborhood_Quality   House_Price  
0            0                     5  2.623829e+05  
1            1                     6  9.852609e+05  
2            0                     9  7.779774e+05  
3            1                     8  2.296989e+05  
4            0                     8  1.041741e+06

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Square_Footage        1000 non-null   int64  
 1   Num_Bedrooms          1000 non-null   int64  
 2   Num_Bathrooms         1000 non-null   int64  
 3   Year_Built            1000 non-null   int64  
 4   Lot_Size              1000 non-null   float64
 5   Garage_Size           1000 non-null   int64  
 6   Neighborhood_Quality  1000 non-null   int64  
 7   House_Price           1000 non-null   float64
dtypes: float64(2), int64(6)
memory usage: 62.6 KB


In [46]:
df.House_Price

0      2.623829e+05
1      9.852609e+05
2      7.779774e+05
3      2.296989e+05
4      1.041741e+06
           ...     
995    7.014940e+05
996    6.837232e+05
997    5.720240e+05
998    9.648653e+05
999    7.425993e+05
Name: House_Price, Length: 1000, dtype: float64

In [47]:
x = df.drop('House_Price',axis=1)
y= df['House_Price']

In [48]:
x

Square_Footage  Num_Bedrooms  Num_Bathrooms  Year_Built  Lot_Size  \
0              1360             2              1        1981  0.599637   
1              4272             3              3        2016  4.753014   
2              3592             1              2        2016  3.634823   
3               966             1              2        1977  2.730667   
4              4926             2              1        1993  4.699073   
..              ...           ...            ...         ...       ...   
995            3261             4              1        1978  2.165110   
996            3179             1              2        1999  2.977123   
997            2606             4              2        1962  4.055067   
998            4723             5              2        1950  1.930921   
999            3268             4              2        1983  3.108790   

     Garage_Size  Neighborhood_Quality  
0              0                     5  
1              1                     6  
2              0                     9  
3              1                     8  
4              0                     8  
..           ...                   ...  
995            2                    10  
996            1                    10  
997            0                     2  
998            0                     7  
999            2                     2  

[1000 rows x 7 columns]

In [49]:
y

0      2.623829e+05
1      9.852609e+05
2      7.779774e+05
3      2.296989e+05
4      1.041741e+06
           ...     
995    7.014940e+05
996    6.837232e+05
997    5.720240e+05
998    9.648653e+05
999    7.425993e+05
Name: House_Price, Length: 1000, dtype: float64

In [50]:
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [51]:
x_scaled

array([[-1.15980323, -0.69383623, -1.18669921, ..., -1.67927849,
        -1.25465753, -0.21312613],
       [ 1.16072443,  0.00700845,  1.25255918, ...,  1.52238989,
        -0.02700828,  0.13342042],
       [ 0.61884297, -1.39468091,  0.03292999, ...,  0.66042215,
        -1.25465753,  1.17306009],
       ...,
       [-0.16688515,  0.70785312,  0.03292999, ...,  0.98437109,
        -1.25465753, -1.25276579],
       [ 1.52011933,  1.4086978 ,  0.03292999, ..., -0.65304553,
        -1.25465753,  0.47996698],
       [ 0.36065239,  0.70785312,  0.03292999, ...,  0.25492526,
         1.20064096, -1.25276579]])

In [52]:
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=.2,random_state=35)

In [53]:
xgb_regression = xgb.XGBRegressor()

In [55]:
xgb_regression.fit(x_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [56]:
xgb_regression.predict(x_test)

array([ 705483.6 ,  187797.4 ,  517696.16,  288536.97,  590350.5 ,
        448835.75,  362469.56,  244127.7 ,  829635.8 ,  503271.66,
        802901.  ,  490703.62,  643385.3 ,  458814.72,  452446.53,
        576392.2 ,  837017.8 ,  222611.75,  327915.4 ,  725169.75,
        513022.9 ,  593723.44,  657590.2 ,  600650.3 ,  197144.98,
        404746.97,  430288.78,  351418.8 ,  284689.47,  730708.9 ,
        462869.78,  613804.25,  829006.44,  885221.2 ,  384199.72,
       1047536.3 ,  309650.66,  893302.25,  507300.06,  882542.56,
        340010.38,  588688.75, 1036204.06,  799926.44,  557490.5 ,
        904408.25,  481848.72,  563330.25,  616438.8 ,  882322.8 ,
        865418.2 ,  461085.25,  371807.88,  728943.6 ,  935179.75,
        298058.53,  798261.3 ,  910081.2 ,  619309.06,  669506.25,
        208405.25, 1010776.6 ,  829289.8 ,  202606.16,  742436.94,
        498771.34,  603559.  ,  868979.7 ,  437371.25,  487852.44,
        278619.16,  390744.56,  879493.06,  849882.  ,  985626

In [57]:
mean_squared_error(y_test,xgb_regression.predict(x_test) )


363237530.00478226

In [59]:
mean_absolute_error(y_test,xgb_regression.predict(x_test))


15590.690843307055

In [60]:
r2_score(y_test,xgb_regression.predict(x_test))


0.9933955814367269

In [63]:
param_grid={
    "n_estimators":[50,100,200],
    "learning_rate":[.01,.1,.2],
    "max_depth":[3,5,7,8,9,11],
    "subsample":[.7,.8,1],
    "colsample_bytree":[.7,.8,.1]
}

In [64]:
grid_search =GridSearchCV(xgb.XGBRegressor(),param_grid,cv=3,n_jobs=1,verbose=2)

In [65]:
grid_search.fit(x_train,y_train)

Fitting 3 folds for each of 486 candidates, totalling 1458 fits
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.7; total time=   0.2s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.7; total time=   0.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.7; total time=   0.1s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=1; total time=   0.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=1; total time=   0.0s
[CV] END colsample_b

GridSearchCV(cv=3,
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, gamma=None,
                                    grow_policy=None, importance_type=None,
                                    interaction_constraints=None,
                                    learning_rate=None, m...
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None,
                                    random_state=None, ...),
             n_jobs=1,
             param_grid={'colsample_bytree': [0.7, 0.8, 0.1],
                         'learning_rate': [0.01, 0.1, 0.2],
                         'max_depth': [3, 5, 7, 8, 9, 11],
                         'n_estimators': [50, 100, 200],
                         'subsample': [0.7, 0.8, 1]},
             verbose=2)

In [66]:
grid_search.best_params_

{'colsample_bytree': 0.8,
 'learning_rate': 0.1,
 'max_depth': 3,
 'n_estimators': 200,
 'subsample': 1}

In [67]:
xgb_regression_best_params = xgb.XGBRegressor(**grid_search.best_params_)

In [68]:
xgb_regression_best_params.fit(x_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.1, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=3, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=200, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [69]:
xgb_regression_best_params.predict(x_test)

array([ 721674.  ,  190432.69,  508913.72,  290484.53,  588318.7 ,
        485591.12,  351856.16,  242872.2 ,  826164.06,  522375.5 ,
        802974.44,  496900.38,  655141.  ,  467588.7 ,  458298.8 ,
        563565.1 ,  856195.56,  201993.22,  335555.7 ,  741402.44,
        524559.5 ,  585018.75,  650081.75,  579753.3 ,  179963.64,
        407675.12,  433178.03,  348490.34,  283019.78,  730397.1 ,
        460926.28,  633290.44,  840891.56,  864648.25,  387583.62,
       1057025.9 ,  345827.66,  901696.7 ,  495632.38,  889681.7 ,
        365681.12,  566557.56, 1036484.94,  798360.44,  553737.56,
        921516.4 ,  505335.1 ,  606005.2 ,  626946.8 ,  882256.  ,
        828035.25,  454739.9 ,  358218.75,  724896.56,  957932.3 ,
        309182.25,  810442.3 ,  929194.7 ,  622813.06,  656421.44,
        210606.1 , 1014436.9 ,  841946.2 ,  202886.22,  748920.  ,
        491022.75,  609596.75,  867693.5 ,  450940.75,  494063.28,
        311927.53,  364911.47,  868037.4 ,  838128.  , 1002355

In [70]:
mean_squared_error(y_test,xgb_regression_best_params.predict(x_test) )


209956076.78884912

In [71]:
mean_absolute_error(y_test,xgb_regression_best_params.predict(x_test))


11488.4078669762

In [72]:
r2_score(y_test,xgb_regression_best_params.predict(x_test))


0.9961825590791843